services:
  registry:
    image: registry:2
    restart: always
    volumes:
      - /container/registry/images:/var/lib/registry
    networks:
      - registry-net

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "[2a00:6020:b0b3:fc00:be24:11ff:fe25:f1bb]:80:80"    # <-- Hinzuf端gen f端r die ACME Challenge
      - "[2a00:6020:b0b3:fc00:be24:11ff:fe25:f1bb]:443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /container/registry/auth:/etc/nginx/auth
      - /container/certbot/conf:/etc/letsencrypt      # <-- Hinzuf端gen
      - ./certbot/www:/var/www/certbot      # <-- Hinzuf端gen
    depends_on:
      - registry
    networks:
      - registry-net

  certbot:                                    # <-- Neuer Service
    image: certbot/certbot
    volumes:
      - /conatiner/certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - registry-net  

networks:
  registry-net:
    driver: bridge

